# https://docs.flutter.dev/development/accessibility-and-localization/internationalization#configuring-the-l10nyaml-file
arb-dir: lib/l10n
template-arb-file: app_zh.arb
output-localization-file: app_localizations.dart
preferred-supported-locales:
- "en"
- "zh"
# - "zh_TW"
# - "zh_Hant"
# - "zh_Hant_TW"
use-deferred-loading: true
untranslated-messages-file: docs/untranslated.json
