# button
delete: Delete
cancel: Cancel
confirm: Confirm
save: Save

# status
success: Operator success
unknown_error: Unknown Error

# component
total_count: "{count} items"
search_count: "Found {count} result"
delete_title: Confirm deletion
delete_confirm: "Do you really want to delete {name}？\n\nIt is unrecoverable！"
# bottom sheet action title
action_title: Actions
empty_body: Empty items!
