// Mocks generated by Mockito 5.0.9 from annotations
// in possystem/test/models/menu/product_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:possystem/models/menu/catalog_model.dart' as _i3;
import 'package:possystem/models/menu/product_model.dart' as _i5;
import 'package:possystem/models/objects/menu_object.dart' as _i2;
import 'package:possystem/services/storage.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeDateTime extends _i1.Fake implements DateTime {}

class _FakeCatalogObject extends _i1.Fake implements _i2.CatalogObject {}

/// A class which mocks [CatalogModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogModel extends _i1.Mock implements _i3.CatalogModel {
  MockCatalogModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  set name(String? _name) => super.noSuchMethod(Invocation.setter(#name, _name),
      returnValueForMissingStub: null);
  @override
  DateTime get createdAt => (super.noSuchMethod(Invocation.getter(#createdAt),
      returnValue: _FakeDateTime()) as DateTime);
  @override
  String get itemCode =>
      (super.noSuchMethod(Invocation.getter(#itemCode), returnValue: '')
          as String);
  @override
  String get code =>
      (super.noSuchMethod(Invocation.getter(#code), returnValue: '') as String);
  @override
  _i4.Stores get storageStore =>
      (super.noSuchMethod(Invocation.getter(#storageStore),
          returnValue: _i4.Stores.menu) as _i4.Stores);
  @override
  int get index =>
      (super.noSuchMethod(Invocation.getter(#index), returnValue: 0) as int);
  @override
  set index(int? _index) =>
      super.noSuchMethod(Invocation.setter(#index, _index),
          returnValueForMissingStub: null);
  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);
  @override
  bool get isNotEmpty =>
      (super.noSuchMethod(Invocation.getter(#isNotEmpty), returnValue: false)
          as bool);
  @override
  List<_i5.ProductModel> get itemList =>
      (super.noSuchMethod(Invocation.getter(#itemList),
          returnValue: <_i5.ProductModel>[]) as List<_i5.ProductModel>);
  @override
  Iterable<_i5.ProductModel> get items =>
      (super.noSuchMethod(Invocation.getter(#items),
          returnValue: <_i5.ProductModel>[]) as Iterable<_i5.ProductModel>);
  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);
  @override
  int get newIndex =>
      (super.noSuchMethod(Invocation.getter(#newIndex), returnValue: 0) as int);
  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  set id(String? _id) => super.noSuchMethod(Invocation.setter(#id, _id),
      returnValueForMissingStub: null);
  @override
  String get prefix =>
      (super.noSuchMethod(Invocation.getter(#prefix), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  void removeFromRepo() =>
      super.noSuchMethod(Invocation.method(#removeFromRepo, []),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> addItemToStorage(_i5.ProductModel? child) =>
      (super.noSuchMethod(Invocation.method(#addItemToStorage, [child]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i6.Future<void>);
  @override
  _i2.CatalogObject toObject() =>
      (super.noSuchMethod(Invocation.method(#toObject, []),
          returnValue: _FakeCatalogObject()) as _i2.CatalogObject);
  @override
  String toString() =>
      (super.noSuchMethod(Invocation.method(#toString, []), returnValue: '')
          as String);
  @override
  void addItem(_i5.ProductModel? item) =>
      super.noSuchMethod(Invocation.method(#addItem, [item]),
          returnValueForMissingStub: null);
  @override
  _i5.ProductModel? getItem(String? id) =>
      (super.noSuchMethod(Invocation.method(#getItem, [id]))
          as _i5.ProductModel?);
  @override
  bool hasItem(String? id) =>
      (super.noSuchMethod(Invocation.method(#hasItem, [id]), returnValue: false)
          as bool);
  @override
  bool hasName(String? name) => (super
          .noSuchMethod(Invocation.method(#hasName, [name]), returnValue: false)
      as bool);
  @override
  void notifyItem() => super.noSuchMethod(Invocation.method(#notifyItem, []),
      returnValueForMissingStub: null);
  @override
  void removeItem(String? id) =>
      super.noSuchMethod(Invocation.method(#removeItem, [id]),
          returnValueForMissingStub: null);
  @override
  void replaceItems(Map<String, _i5.ProductModel>? map) =>
      super.noSuchMethod(Invocation.method(#replaceItems, [map]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> setItem(_i5.ProductModel? item) =>
      (super.noSuchMethod(Invocation.method(#setItem, [item]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> reorderItems(List<_i5.ProductModel>? items) =>
      (super.noSuchMethod(Invocation.method(#reorderItems, [items]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> update(_i2.CatalogObject? object) =>
      (super.noSuchMethod(Invocation.method(#update, [object]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> remove() =>
      (super.noSuchMethod(Invocation.method(#remove, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i6.Future<void>);
  @override
  void addListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
