// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kDebugMode, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }

    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return kDebugMode ? androidDev : android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfu1cLBlQaAcEFkbK81CZx3xJthZvgGw4',
    appId: '1:747759991726:android:2943f641957927a1',
    messagingSenderId: '747759991726',
    projectId: 'android-pos-syst-1553173065663',
    databaseURL: 'https://android-pos-syst-1553173065663.firebaseio.com',
    storageBucket: 'android-pos-syst-1553173065663.appspot.com',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyDb_WeFh5nG-l0ScDhVYYnyBYPwbykFPAY',
    appId: '1:53696347946:android:ac27f47cd1ca1e9c556853',
    messagingSenderId: '53696347946',
    projectId: 'flutter-pos-system-debug',
    storageBucket: 'flutter-pos-system-debug.appspot.com',
  );
}
