# button
delete: 刪除
cancel: 取消
confirm: 確認
save: 儲存

unknown_error: 發生未知錯誤

total_count: "總共 {count} 項"
search_count: "搜尋到 {count} 個結果"
delete_title: 確認刪除通知
# bottom sheet action title
action_title: 執行動作
empty_body: 哎呀！這裡還是空的
