# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test locally - build only"
  lane :test do
    sh "flutter build ios --no-codesign"
  end

  desc "Build for development testing"
  lane :build_dev do
    sh "flutter build ios --no-codesign --dart-define=appFlavor=dev --dart-define=logLevel=info"
  end

  desc "Build for production"
  lane :build_prod do
    sh "flutter build ios --no-codesign --dart-define=appFlavor=prod --dart-define=logLevel=info"
  end

  desc "Submit to TestFlight"
  lane :beta do
    # Build the app
    sh "flutter build ios --dart-define=appFlavor=prod --dart-define=logLevel=info"
    
    # Code signing and upload would go here when certificates are available
    # build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    # upload_to_testflight
  end

  desc "Submit to App Store"
  lane :release do
    # Build the app
    sh "flutter build ios --dart-define=appFlavor=prod --dart-define=logLevel=info"
    
    # Code signing and upload would go here when certificates are available
    # build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    # upload_to_app_store
  end
end