# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test locally - build only"
  lane :test do
    sh "flutter build ios --no-codesign"
  end

  desc "Build for development testing"
  lane :build_dev do
    sh "flutter build ios --no-codesign --dart-define=appFlavor=dev --dart-define=logLevel=info"
  end

  desc "Build for production"
  lane :build_prod do
    sh "flutter build ios --no-codesign --dart-define=appFlavor=prod --dart-define=logLevel=info"
  end

  desc "Submit a new Internal Build to TestFlight (internal testing)"
  lane :internal do
    # Build the app for development
    sh "flutter build ipa --export-options-plist=ExportOptions.plist --dart-define=appFlavor=dev --dart-define=logLevel=info"
    
    # Upload to TestFlight for internal testing
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      ipa: "../../build/ios/ipa/*.ipa",
      api_key_path: "fastlane-api-key.json",
    )
  end

  desc "Submit a new Beta Build to TestFlight (external testing)"
  lane :beta do
    # Build the app for production
    sh "flutter build ipa --export-options-plist=ExportOptions.plist --dart-define=appFlavor=prod --dart-define=logLevel=info"
    
    # Upload to TestFlight for external testing
    upload_to_testflight(
      skip_waiting_for_build_processing: false,
      ipa: "../../build/ios/ipa/*.ipa",
      api_key_path: "fastlane-api-key.json",
    )
  end

  desc "Promote beta to production (App Store)"
  lane :promote_to_production do
    # Deliver the latest build to App Store
    deliver(
      skip_metadata: false,
      skip_screenshots: false,
      skip_binary_upload: true,
      submit_for_review: false,
      automatic_release: false,
      api_key_path: "fastlane-api-key.json",
      build_number: ENV['VERSION_CODE'],
    )
  end
end
