// Mocks generated by Mockito 5.4.5 from annotations
// in possystem/test/mocks/mock_database.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:possystem/services/database.dart' as _i4;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeQueryCursor_2 extends _i1.SmartFake implements _i2.QueryCursor {
  _FakeQueryCursor_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeBatch_3 extends _i1.SmartFake implements _i2.Batch {
  _FakeBatch_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i4.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_0(this, Invocation.getter(#db)),
      ) as _i2.Database);

  @override
  set db(_i2.Database? _db) => super.noSuchMethod(
        Invocation.setter(#db, _db),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<List<Object?>> batchUpdate(
    String? table,
    List<Map<String, Object?>>? data, {
    required String? where,
    required List<List<Object>>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [table, data],
          {#where: where, #whereArgs: whereArgs},
        ),
        returnValue: _i3.Future<List<Object?>>.value(<Object?>[]),
      ) as _i3.Future<List<Object?>>);

  @override
  _i3.Future<void> reset(
    String? table, [
    _i3.Future<void> Function(String)? del = _i2.deleteDatabase,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(#reset, [table, del]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int?> count(
    String? table, {
    String? where,
    List<Object>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #count,
          [table],
          {#where: where, #whereArgs: whereArgs},
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);

  @override
  _i3.Future<void> delete(
    String? table,
    Object? id, {
    String? keyName = 'id',
  }) =>
      (super.noSuchMethod(
        Invocation.method(#delete, [table, id], {#keyName: keyName}),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> initialize({
    String? path,
    _i2.DatabaseFactory? factory,
    bool? logWhenQuery = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#initialize, [], {
          #path: path,
          #factory: factory,
          #logWhenQuery: logWhenQuery,
        }),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> push(String? table, Map<String, Object?>? data) => (super.noSuchMethod(
        Invocation.method(#push, [table, data]),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<T> transaction<T>(
    _i3.Future<T> Function(_i2.DatabaseExecutor)? action,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#transaction, [action]),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(#transaction, [action]),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(#transaction, [action]),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<List<Map<String, Object?>>> query(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
    List<String>? columns,
    _i4.JoinQuery? join,
    String? groupBy,
    String? orderBy,
    int? limit,
    int? offset = 0,
    bool? escapeTable = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
            #columns: columns,
            #join: join,
            #groupBy: groupBy,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
            #escapeTable: escapeTable,
          },
        ),
        returnValue: _i3.Future<List<Map<String, Object?>>>.value(
          <Map<String, Object?>>[],
        ),
      ) as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<int> update(
    String? table,
    Object? key,
    Map<String, Object?>? data, {
    dynamic keyName = 'id',
  }) =>
      (super.noSuchMethod(
        Invocation.method(#update, [table, key, data], {#keyName: keyName}),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [DatabaseExecutor].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseExecutor extends _i1.Mock implements _i2.DatabaseExecutor {
  MockDatabaseExecutor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Database get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabase_0(this, Invocation.getter(#database)),
      ) as _i2.Database);

  @override
  _i3.Future<void> execute(String? sql, [List<Object?>? arguments]) => (super.noSuchMethod(
        Invocation.method(#execute, [sql, arguments]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> rawInsert(String? sql, [List<Object?>? arguments]) => (super.noSuchMethod(
        Invocation.method(#rawInsert, [sql, arguments]),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> insert(
    String? table,
    Map<String, Object?>? values, {
    String? nullColumnHack,
    _i2.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [table, values],
          {
            #nullColumnHack: nullColumnHack,
            #conflictAlgorithm: conflictAlgorithm,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, Object?>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<Map<String, Object?>>>.value(
          <Map<String, Object?>>[],
        ),
      ) as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<List<Map<String, Object?>>> rawQuery(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(#rawQuery, [sql, arguments]),
        returnValue: _i3.Future<List<Map<String, Object?>>>.value(
          <Map<String, Object?>>[],
        ),
      ) as _i3.Future<List<Map<String, Object?>>>);

  @override
  _i3.Future<_i2.QueryCursor> rawQueryCursor(
    String? sql,
    List<Object?>? arguments, {
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQueryCursor,
          [sql, arguments],
          {#bufferSize: bufferSize},
        ),
        returnValue: _i3.Future<_i2.QueryCursor>.value(
          _FakeQueryCursor_2(
            this,
            Invocation.method(
              #rawQueryCursor,
              [sql, arguments],
              {#bufferSize: bufferSize},
            ),
          ),
        ),
      ) as _i3.Future<_i2.QueryCursor>);

  @override
  _i3.Future<_i2.QueryCursor> queryCursor(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryCursor,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
            #bufferSize: bufferSize,
          },
        ),
        returnValue: _i3.Future<_i2.QueryCursor>.value(
          _FakeQueryCursor_2(
            this,
            Invocation.method(
              #queryCursor,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
                #bufferSize: bufferSize,
              },
            ),
          ),
        ),
      ) as _i3.Future<_i2.QueryCursor>);

  @override
  _i3.Future<int> rawUpdate(String? sql, [List<Object?>? arguments]) => (super.noSuchMethod(
        Invocation.method(#rawUpdate, [sql, arguments]),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> update(
    String? table,
    Map<String, Object?>? values, {
    String? where,
    List<Object?>? whereArgs,
    _i2.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table, values],
          {
            #where: where,
            #whereArgs: whereArgs,
            #conflictAlgorithm: conflictAlgorithm,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> rawDelete(String? sql, [List<Object?>? arguments]) => (super.noSuchMethod(
        Invocation.method(#rawDelete, [sql, arguments]),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> delete(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {#where: where, #whereArgs: whereArgs},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i2.Batch batch() => (super.noSuchMethod(
        Invocation.method(#batch, []),
        returnValue: _FakeBatch_3(this, Invocation.method(#batch, [])),
      ) as _i2.Batch);
}

/// A class which mocks [Batch].
///
/// See the documentation for Mockito's code generation for more information.
class MockBatch extends _i1.Mock implements _i2.Batch {
  MockBatch() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get length => (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);

  @override
  _i3.Future<List<Object?>> commit({
    bool? exclusive,
    bool? noResult,
    bool? continueOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#commit, [], {
          #exclusive: exclusive,
          #noResult: noResult,
          #continueOnError: continueOnError,
        }),
        returnValue: _i3.Future<List<Object?>>.value(<Object?>[]),
      ) as _i3.Future<List<Object?>>);

  @override
  _i3.Future<List<Object?>> apply({bool? noResult, bool? continueOnError}) => (super.noSuchMethod(
        Invocation.method(#apply, [], {
          #noResult: noResult,
          #continueOnError: continueOnError,
        }),
        returnValue: _i3.Future<List<Object?>>.value(<Object?>[]),
      ) as _i3.Future<List<Object?>>);

  @override
  void rawInsert(String? sql, [List<Object?>? arguments]) => super.noSuchMethod(
        Invocation.method(#rawInsert, [sql, arguments]),
        returnValueForMissingStub: null,
      );

  @override
  void insert(
    String? table,
    Map<String, Object?>? values, {
    String? nullColumnHack,
    _i2.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #insert,
          [table, values],
          {#nullColumnHack: nullColumnHack, #conflictAlgorithm: conflictAlgorithm},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void rawUpdate(String? sql, [List<Object?>? arguments]) => super.noSuchMethod(
        Invocation.method(#rawUpdate, [sql, arguments]),
        returnValueForMissingStub: null,
      );

  @override
  void update(
    String? table,
    Map<String, Object?>? values, {
    String? where,
    List<Object?>? whereArgs,
    _i2.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [table, values],
          {
            #where: where,
            #whereArgs: whereArgs,
            #conflictAlgorithm: conflictAlgorithm,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void rawDelete(String? sql, [List<Object?>? arguments]) => super.noSuchMethod(
        Invocation.method(#rawDelete, [sql, arguments]),
        returnValueForMissingStub: null,
      );

  @override
  void delete(String? table, {String? where, List<Object?>? whereArgs}) => super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {#where: where, #whereArgs: whereArgs},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void execute(String? sql, [List<Object?>? arguments]) => super.noSuchMethod(
        Invocation.method(#execute, [sql, arguments]),
        returnValueForMissingStub: null,
      );

  @override
  void query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #distinct: distinct,
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #groupBy: groupBy,
            #having: having,
            #orderBy: orderBy,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void rawQuery(String? sql, [List<Object?>? arguments]) => super.noSuchMethod(
        Invocation.method(#rawQuery, [sql, arguments]),
        returnValueForMissingStub: null,
      );
}
