// Mocks generated by Mockito 5.4.6 from annotations
// in possystem/test/mocks/mock_google_api.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:_discoveryapis_commons/_discoveryapis_commons.dart' as _i6;
import 'package:googleapis/drive/v3.dart' as _i2;
import 'package:googleapis/shared.dart' as _i3;
import 'package:googleapis/sheets/v4.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAboutResource_0 extends _i1.SmartFake implements _i2.AboutResource {
  _FakeAboutResource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccessproposalsResource_1 extends _i1.SmartFake implements _i2.AccessproposalsResource {
  _FakeAccessproposalsResource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppsResource_2 extends _i1.SmartFake implements _i2.AppsResource {
  _FakeAppsResource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChangesResource_3 extends _i1.SmartFake implements _i2.ChangesResource {
  _FakeChangesResource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelsResource_4 extends _i1.SmartFake implements _i2.ChannelsResource {
  _FakeChannelsResource_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommentsResource_5 extends _i1.SmartFake implements _i2.CommentsResource {
  _FakeCommentsResource_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDrivesResource_6 extends _i1.SmartFake implements _i2.DrivesResource {
  _FakeDrivesResource_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFilesResource_7 extends _i1.SmartFake implements _i2.FilesResource {
  _FakeFilesResource_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOperationsResource_8 extends _i1.SmartFake implements _i2.OperationsResource {
  _FakeOperationsResource_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePermissionsResource_9 extends _i1.SmartFake implements _i2.PermissionsResource {
  _FakePermissionsResource_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRepliesResource_10 extends _i1.SmartFake implements _i2.RepliesResource {
  _FakeRepliesResource_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRevisionsResource_11 extends _i1.SmartFake implements _i2.RevisionsResource {
  _FakeRevisionsResource_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTeamdrivesResource_12 extends _i1.SmartFake implements _i2.TeamdrivesResource {
  _FakeTeamdrivesResource_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_13 extends _i1.SmartFake implements _i2.File {
  _FakeFile_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOperation_14 extends _i1.SmartFake implements _i2.Operation {
  _FakeOperation_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedIds_15 extends _i1.SmartFake implements _i2.GeneratedIds {
  _FakeGeneratedIds_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_16 extends _i1.SmartFake implements Object {
  _FakeObject_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileList_17 extends _i1.SmartFake implements _i2.FileList {
  _FakeFileList_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLabelList_18 extends _i1.SmartFake implements _i2.LabelList {
  _FakeLabelList_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModifyLabelsResponse_19 extends _i1.SmartFake implements _i2.ModifyLabelsResponse {
  _FakeModifyLabelsResponse_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$Channel01_20 extends _i1.SmartFake implements _i3.$Channel01 {
  _Fake$Channel01_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpreadsheetsResource_21 extends _i1.SmartFake implements _i4.SpreadsheetsResource {
  _FakeSpreadsheetsResource_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpreadsheetsDeveloperMetadataResource_22 extends _i1.SmartFake
    implements _i4.SpreadsheetsDeveloperMetadataResource {
  _FakeSpreadsheetsDeveloperMetadataResource_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpreadsheetsSheetsResource_23 extends _i1.SmartFake implements _i4.SpreadsheetsSheetsResource {
  _FakeSpreadsheetsSheetsResource_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpreadsheetsValuesResource_24 extends _i1.SmartFake implements _i4.SpreadsheetsValuesResource {
  _FakeSpreadsheetsValuesResource_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchUpdateSpreadsheetResponse_25 extends _i1.SmartFake implements _i4.BatchUpdateSpreadsheetResponse {
  _FakeBatchUpdateSpreadsheetResponse_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpreadsheet_26 extends _i1.SmartFake implements _i4.Spreadsheet {
  _FakeSpreadsheet_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppendValuesResponse_27 extends _i1.SmartFake implements _i4.AppendValuesResponse {
  _FakeAppendValuesResponse_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchClearValuesResponse_28 extends _i1.SmartFake implements _i4.BatchClearValuesResponse {
  _FakeBatchClearValuesResponse_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchClearValuesByDataFilterResponse_29 extends _i1.SmartFake
    implements _i4.BatchClearValuesByDataFilterResponse {
  _FakeBatchClearValuesByDataFilterResponse_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchGetValuesResponse_30 extends _i1.SmartFake implements _i4.BatchGetValuesResponse {
  _FakeBatchGetValuesResponse_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchGetValuesByDataFilterResponse_31 extends _i1.SmartFake
    implements _i4.BatchGetValuesByDataFilterResponse {
  _FakeBatchGetValuesByDataFilterResponse_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchUpdateValuesResponse_32 extends _i1.SmartFake implements _i4.BatchUpdateValuesResponse {
  _FakeBatchUpdateValuesResponse_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchUpdateValuesByDataFilterResponse_33 extends _i1.SmartFake
    implements _i4.BatchUpdateValuesByDataFilterResponse {
  _FakeBatchUpdateValuesByDataFilterResponse_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClearValuesResponse_34 extends _i1.SmartFake implements _i4.ClearValuesResponse {
  _FakeClearValuesResponse_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueRange_35 extends _i1.SmartFake implements _i4.ValueRange {
  _FakeValueRange_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateValuesResponse_36 extends _i1.SmartFake implements _i4.UpdateValuesResponse {
  _FakeUpdateValuesResponse_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DriveApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveApi extends _i1.Mock implements _i2.DriveApi {
  MockDriveApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AboutResource get about => (super.noSuchMethod(
        Invocation.getter(#about),
        returnValue: _FakeAboutResource_0(
          this,
          Invocation.getter(#about),
        ),
      ) as _i2.AboutResource);

  @override
  _i2.AccessproposalsResource get accessproposals => (super.noSuchMethod(
        Invocation.getter(#accessproposals),
        returnValue: _FakeAccessproposalsResource_1(
          this,
          Invocation.getter(#accessproposals),
        ),
      ) as _i2.AccessproposalsResource);

  @override
  _i2.AppsResource get apps => (super.noSuchMethod(
        Invocation.getter(#apps),
        returnValue: _FakeAppsResource_2(
          this,
          Invocation.getter(#apps),
        ),
      ) as _i2.AppsResource);

  @override
  _i2.ChangesResource get changes => (super.noSuchMethod(
        Invocation.getter(#changes),
        returnValue: _FakeChangesResource_3(
          this,
          Invocation.getter(#changes),
        ),
      ) as _i2.ChangesResource);

  @override
  _i2.ChannelsResource get channels => (super.noSuchMethod(
        Invocation.getter(#channels),
        returnValue: _FakeChannelsResource_4(
          this,
          Invocation.getter(#channels),
        ),
      ) as _i2.ChannelsResource);

  @override
  _i2.CommentsResource get comments => (super.noSuchMethod(
        Invocation.getter(#comments),
        returnValue: _FakeCommentsResource_5(
          this,
          Invocation.getter(#comments),
        ),
      ) as _i2.CommentsResource);

  @override
  _i2.DrivesResource get drives => (super.noSuchMethod(
        Invocation.getter(#drives),
        returnValue: _FakeDrivesResource_6(
          this,
          Invocation.getter(#drives),
        ),
      ) as _i2.DrivesResource);

  @override
  _i2.FilesResource get files => (super.noSuchMethod(
        Invocation.getter(#files),
        returnValue: _FakeFilesResource_7(
          this,
          Invocation.getter(#files),
        ),
      ) as _i2.FilesResource);

  @override
  _i2.OperationsResource get operations => (super.noSuchMethod(
        Invocation.getter(#operations),
        returnValue: _FakeOperationsResource_8(
          this,
          Invocation.getter(#operations),
        ),
      ) as _i2.OperationsResource);

  @override
  _i2.PermissionsResource get permissions => (super.noSuchMethod(
        Invocation.getter(#permissions),
        returnValue: _FakePermissionsResource_9(
          this,
          Invocation.getter(#permissions),
        ),
      ) as _i2.PermissionsResource);

  @override
  _i2.RepliesResource get replies => (super.noSuchMethod(
        Invocation.getter(#replies),
        returnValue: _FakeRepliesResource_10(
          this,
          Invocation.getter(#replies),
        ),
      ) as _i2.RepliesResource);

  @override
  _i2.RevisionsResource get revisions => (super.noSuchMethod(
        Invocation.getter(#revisions),
        returnValue: _FakeRevisionsResource_11(
          this,
          Invocation.getter(#revisions),
        ),
      ) as _i2.RevisionsResource);

  @override
  _i2.TeamdrivesResource get teamdrives => (super.noSuchMethod(
        Invocation.getter(#teamdrives),
        returnValue: _FakeTeamdrivesResource_12(
          this,
          Invocation.getter(#teamdrives),
        ),
      ) as _i2.TeamdrivesResource);
}

/// A class which mocks [FilesResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilesResource extends _i1.Mock implements _i2.FilesResource {
  MockFilesResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.File> copy(
    _i2.File? request,
    String? fileId, {
    bool? enforceSingleParent,
    bool? ignoreDefaultVisibility,
    String? includeLabels,
    String? includePermissionsForView,
    bool? keepRevisionForever,
    String? ocrLanguage,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copy,
          [
            request,
            fileId,
          ],
          {
            #enforceSingleParent: enforceSingleParent,
            #ignoreDefaultVisibility: ignoreDefaultVisibility,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #keepRevisionForever: keepRevisionForever,
            #ocrLanguage: ocrLanguage,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i2.File>.value(_FakeFile_13(
          this,
          Invocation.method(
            #copy,
            [
              request,
              fileId,
            ],
            {
              #enforceSingleParent: enforceSingleParent,
              #ignoreDefaultVisibility: ignoreDefaultVisibility,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #keepRevisionForever: keepRevisionForever,
              #ocrLanguage: ocrLanguage,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i2.File>);

  @override
  _i5.Future<_i2.File> create(
    _i2.File? request, {
    bool? enforceSingleParent,
    bool? ignoreDefaultVisibility,
    String? includeLabels,
    String? includePermissionsForView,
    bool? keepRevisionForever,
    String? ocrLanguage,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    bool? useContentAsIndexableText,
    String? $fields,
    _i6.UploadOptions? uploadOptions = _i6.UploadOptions.defaultOptions,
    _i6.Media? uploadMedia,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [request],
          {
            #enforceSingleParent: enforceSingleParent,
            #ignoreDefaultVisibility: ignoreDefaultVisibility,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #keepRevisionForever: keepRevisionForever,
            #ocrLanguage: ocrLanguage,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #useContentAsIndexableText: useContentAsIndexableText,
            #$fields: $fields,
            #uploadOptions: uploadOptions,
            #uploadMedia: uploadMedia,
          },
        ),
        returnValue: _i5.Future<_i2.File>.value(_FakeFile_13(
          this,
          Invocation.method(
            #create,
            [request],
            {
              #enforceSingleParent: enforceSingleParent,
              #ignoreDefaultVisibility: ignoreDefaultVisibility,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #keepRevisionForever: keepRevisionForever,
              #ocrLanguage: ocrLanguage,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #useContentAsIndexableText: useContentAsIndexableText,
              #$fields: $fields,
              #uploadOptions: uploadOptions,
              #uploadMedia: uploadMedia,
            },
          ),
        )),
      ) as _i5.Future<_i2.File>);

  @override
  _i5.Future<void> delete(
    String? fileId, {
    bool? enforceSingleParent,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [fileId],
          {
            #enforceSingleParent: enforceSingleParent,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Operation> download(
    String? fileId, {
    String? mimeType,
    String? revisionId,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [fileId],
          {
            #mimeType: mimeType,
            #revisionId: revisionId,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i2.Operation>.value(_FakeOperation_14(
          this,
          Invocation.method(
            #download,
            [fileId],
            {
              #mimeType: mimeType,
              #revisionId: revisionId,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i2.Operation>);

  @override
  _i5.Future<void> emptyTrash({
    String? driveId,
    bool? enforceSingleParent,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #emptyTrash,
          [],
          {
            #driveId: driveId,
            #enforceSingleParent: enforceSingleParent,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.Media?> export(
    String? fileId,
    String? mimeType, {
    String? $fields,
    _i6.DownloadOptions? downloadOptions = _i6.DownloadOptions.metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #export,
          [
            fileId,
            mimeType,
          ],
          {
            #$fields: $fields,
            #downloadOptions: downloadOptions,
          },
        ),
        returnValue: _i5.Future<_i6.Media?>.value(),
      ) as _i5.Future<_i6.Media?>);

  @override
  _i5.Future<_i2.GeneratedIds> generateIds({
    int? count,
    String? space,
    String? type,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateIds,
          [],
          {
            #count: count,
            #space: space,
            #type: type,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i2.GeneratedIds>.value(_FakeGeneratedIds_15(
          this,
          Invocation.method(
            #generateIds,
            [],
            {
              #count: count,
              #space: space,
              #type: type,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i2.GeneratedIds>);

  @override
  _i5.Future<Object> get(
    String? fileId, {
    bool? acknowledgeAbuse,
    String? includeLabels,
    String? includePermissionsForView,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
    _i6.DownloadOptions? downloadOptions = _i6.DownloadOptions.metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [fileId],
          {
            #acknowledgeAbuse: acknowledgeAbuse,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
            #downloadOptions: downloadOptions,
          },
        ),
        returnValue: _i5.Future<Object>.value(_FakeObject_16(
          this,
          Invocation.method(
            #get,
            [fileId],
            {
              #acknowledgeAbuse: acknowledgeAbuse,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #$fields: $fields,
              #downloadOptions: downloadOptions,
            },
          ),
        )),
      ) as _i5.Future<Object>);

  @override
  _i5.Future<_i2.FileList> list({
    String? corpora,
    String? corpus,
    String? driveId,
    bool? includeItemsFromAllDrives,
    String? includeLabels,
    String? includePermissionsForView,
    bool? includeTeamDriveItems,
    String? orderBy,
    int? pageSize,
    String? pageToken,
    String? q,
    String? spaces,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? teamDriveId,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #corpora: corpora,
            #corpus: corpus,
            #driveId: driveId,
            #includeItemsFromAllDrives: includeItemsFromAllDrives,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #includeTeamDriveItems: includeTeamDriveItems,
            #orderBy: orderBy,
            #pageSize: pageSize,
            #pageToken: pageToken,
            #q: q,
            #spaces: spaces,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #teamDriveId: teamDriveId,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i2.FileList>.value(_FakeFileList_17(
          this,
          Invocation.method(
            #list,
            [],
            {
              #corpora: corpora,
              #corpus: corpus,
              #driveId: driveId,
              #includeItemsFromAllDrives: includeItemsFromAllDrives,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #includeTeamDriveItems: includeTeamDriveItems,
              #orderBy: orderBy,
              #pageSize: pageSize,
              #pageToken: pageToken,
              #q: q,
              #spaces: spaces,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #teamDriveId: teamDriveId,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i2.FileList>);

  @override
  _i5.Future<_i2.LabelList> listLabels(
    String? fileId, {
    int? maxResults,
    String? pageToken,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLabels,
          [fileId],
          {
            #maxResults: maxResults,
            #pageToken: pageToken,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i2.LabelList>.value(_FakeLabelList_18(
          this,
          Invocation.method(
            #listLabels,
            [fileId],
            {
              #maxResults: maxResults,
              #pageToken: pageToken,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i2.LabelList>);

  @override
  _i5.Future<_i2.ModifyLabelsResponse> modifyLabels(
    _i2.ModifyLabelsRequest? request,
    String? fileId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modifyLabels,
          [
            request,
            fileId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i5.Future<_i2.ModifyLabelsResponse>.value(_FakeModifyLabelsResponse_19(
          this,
          Invocation.method(
            #modifyLabels,
            [
              request,
              fileId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i5.Future<_i2.ModifyLabelsResponse>);

  @override
  _i5.Future<_i2.File> update(
    _i2.File? request,
    String? fileId, {
    String? addParents,
    bool? enforceSingleParent,
    String? includeLabels,
    String? includePermissionsForView,
    bool? keepRevisionForever,
    String? ocrLanguage,
    String? removeParents,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    bool? useContentAsIndexableText,
    String? $fields,
    _i6.UploadOptions? uploadOptions = _i6.UploadOptions.defaultOptions,
    _i6.Media? uploadMedia,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            request,
            fileId,
          ],
          {
            #addParents: addParents,
            #enforceSingleParent: enforceSingleParent,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #keepRevisionForever: keepRevisionForever,
            #ocrLanguage: ocrLanguage,
            #removeParents: removeParents,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #useContentAsIndexableText: useContentAsIndexableText,
            #$fields: $fields,
            #uploadOptions: uploadOptions,
            #uploadMedia: uploadMedia,
          },
        ),
        returnValue: _i5.Future<_i2.File>.value(_FakeFile_13(
          this,
          Invocation.method(
            #update,
            [
              request,
              fileId,
            ],
            {
              #addParents: addParents,
              #enforceSingleParent: enforceSingleParent,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #keepRevisionForever: keepRevisionForever,
              #ocrLanguage: ocrLanguage,
              #removeParents: removeParents,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #useContentAsIndexableText: useContentAsIndexableText,
              #$fields: $fields,
              #uploadOptions: uploadOptions,
              #uploadMedia: uploadMedia,
            },
          ),
        )),
      ) as _i5.Future<_i2.File>);

  @override
  _i5.Future<_i3.$Channel01> watch(
    _i3.$Channel01? request,
    String? fileId, {
    bool? acknowledgeAbuse,
    String? includeLabels,
    String? includePermissionsForView,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [
            request,
            fileId,
          ],
          {
            #acknowledgeAbuse: acknowledgeAbuse,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i3.$Channel01>.value(_Fake$Channel01_20(
          this,
          Invocation.method(
            #watch,
            [
              request,
              fileId,
            ],
            {
              #acknowledgeAbuse: acknowledgeAbuse,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i3.$Channel01>);
}

/// A class which mocks [SheetsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetsApi extends _i1.Mock implements _i4.SheetsApi {
  MockSheetsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SpreadsheetsResource get spreadsheets => (super.noSuchMethod(
        Invocation.getter(#spreadsheets),
        returnValue: _FakeSpreadsheetsResource_21(
          this,
          Invocation.getter(#spreadsheets),
        ),
      ) as _i4.SpreadsheetsResource);
}

/// A class which mocks [SpreadsheetsResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpreadsheetsResource extends _i1.Mock implements _i4.SpreadsheetsResource {
  MockSpreadsheetsResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SpreadsheetsDeveloperMetadataResource get developerMetadata => (super.noSuchMethod(
        Invocation.getter(#developerMetadata),
        returnValue: _FakeSpreadsheetsDeveloperMetadataResource_22(
          this,
          Invocation.getter(#developerMetadata),
        ),
      ) as _i4.SpreadsheetsDeveloperMetadataResource);

  @override
  _i4.SpreadsheetsSheetsResource get sheets => (super.noSuchMethod(
        Invocation.getter(#sheets),
        returnValue: _FakeSpreadsheetsSheetsResource_23(
          this,
          Invocation.getter(#sheets),
        ),
      ) as _i4.SpreadsheetsSheetsResource);

  @override
  _i4.SpreadsheetsValuesResource get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: _FakeSpreadsheetsValuesResource_24(
          this,
          Invocation.getter(#values),
        ),
      ) as _i4.SpreadsheetsValuesResource);

  @override
  _i5.Future<_i4.BatchUpdateSpreadsheetResponse> batchUpdate(
    _i4.BatchUpdateSpreadsheetRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i5.Future<_i4.BatchUpdateSpreadsheetResponse>.value(_FakeBatchUpdateSpreadsheetResponse_25(
          this,
          Invocation.method(
            #batchUpdate,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i5.Future<_i4.BatchUpdateSpreadsheetResponse>);

  @override
  _i5.Future<_i4.Spreadsheet> create(
    _i4.Spreadsheet? request, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [request],
          {#$fields: $fields},
        ),
        returnValue: _i5.Future<_i4.Spreadsheet>.value(_FakeSpreadsheet_26(
          this,
          Invocation.method(
            #create,
            [request],
            {#$fields: $fields},
          ),
        )),
      ) as _i5.Future<_i4.Spreadsheet>);

  @override
  _i5.Future<_i4.Spreadsheet> get(
    String? spreadsheetId, {
    bool? includeGridData,
    List<String>? ranges,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [spreadsheetId],
          {
            #includeGridData: includeGridData,
            #ranges: ranges,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i4.Spreadsheet>.value(_FakeSpreadsheet_26(
          this,
          Invocation.method(
            #get,
            [spreadsheetId],
            {
              #includeGridData: includeGridData,
              #ranges: ranges,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i4.Spreadsheet>);

  @override
  _i5.Future<_i4.Spreadsheet> getByDataFilter(
    _i4.GetSpreadsheetByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByDataFilter,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i5.Future<_i4.Spreadsheet>.value(_FakeSpreadsheet_26(
          this,
          Invocation.method(
            #getByDataFilter,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i5.Future<_i4.Spreadsheet>);
}

/// A class which mocks [SpreadsheetsValuesResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpreadsheetsValuesResource extends _i1.Mock implements _i4.SpreadsheetsValuesResource {
  MockSpreadsheetsValuesResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.AppendValuesResponse> append(
    _i4.ValueRange? request,
    String? spreadsheetId,
    String? range, {
    bool? includeValuesInResponse,
    String? insertDataOption,
    String? responseDateTimeRenderOption,
    String? responseValueRenderOption,
    String? valueInputOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #append,
          [
            request,
            spreadsheetId,
            range,
          ],
          {
            #includeValuesInResponse: includeValuesInResponse,
            #insertDataOption: insertDataOption,
            #responseDateTimeRenderOption: responseDateTimeRenderOption,
            #responseValueRenderOption: responseValueRenderOption,
            #valueInputOption: valueInputOption,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i4.AppendValuesResponse>.value(_FakeAppendValuesResponse_27(
          this,
          Invocation.method(
            #append,
            [
              request,
              spreadsheetId,
              range,
            ],
            {
              #includeValuesInResponse: includeValuesInResponse,
              #insertDataOption: insertDataOption,
              #responseDateTimeRenderOption: responseDateTimeRenderOption,
              #responseValueRenderOption: responseValueRenderOption,
              #valueInputOption: valueInputOption,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i4.AppendValuesResponse>);

  @override
  _i5.Future<_i4.BatchClearValuesResponse> batchClear(
    _i4.BatchClearValuesRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchClear,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i5.Future<_i4.BatchClearValuesResponse>.value(_FakeBatchClearValuesResponse_28(
          this,
          Invocation.method(
            #batchClear,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i5.Future<_i4.BatchClearValuesResponse>);

  @override
  _i5.Future<_i4.BatchClearValuesByDataFilterResponse> batchClearByDataFilter(
    _i4.BatchClearValuesByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchClearByDataFilter,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue:
            _i5.Future<_i4.BatchClearValuesByDataFilterResponse>.value(_FakeBatchClearValuesByDataFilterResponse_29(
          this,
          Invocation.method(
            #batchClearByDataFilter,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i5.Future<_i4.BatchClearValuesByDataFilterResponse>);

  @override
  _i5.Future<_i4.BatchGetValuesResponse> batchGet(
    String? spreadsheetId, {
    String? dateTimeRenderOption,
    String? majorDimension,
    List<String>? ranges,
    String? valueRenderOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchGet,
          [spreadsheetId],
          {
            #dateTimeRenderOption: dateTimeRenderOption,
            #majorDimension: majorDimension,
            #ranges: ranges,
            #valueRenderOption: valueRenderOption,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i4.BatchGetValuesResponse>.value(_FakeBatchGetValuesResponse_30(
          this,
          Invocation.method(
            #batchGet,
            [spreadsheetId],
            {
              #dateTimeRenderOption: dateTimeRenderOption,
              #majorDimension: majorDimension,
              #ranges: ranges,
              #valueRenderOption: valueRenderOption,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i4.BatchGetValuesResponse>);

  @override
  _i5.Future<_i4.BatchGetValuesByDataFilterResponse> batchGetByDataFilter(
    _i4.BatchGetValuesByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchGetByDataFilter,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue:
            _i5.Future<_i4.BatchGetValuesByDataFilterResponse>.value(_FakeBatchGetValuesByDataFilterResponse_31(
          this,
          Invocation.method(
            #batchGetByDataFilter,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i5.Future<_i4.BatchGetValuesByDataFilterResponse>);

  @override
  _i5.Future<_i4.BatchUpdateValuesResponse> batchUpdate(
    _i4.BatchUpdateValuesRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i5.Future<_i4.BatchUpdateValuesResponse>.value(_FakeBatchUpdateValuesResponse_32(
          this,
          Invocation.method(
            #batchUpdate,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i5.Future<_i4.BatchUpdateValuesResponse>);

  @override
  _i5.Future<_i4.BatchUpdateValuesByDataFilterResponse> batchUpdateByDataFilter(
    _i4.BatchUpdateValuesByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateByDataFilter,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue:
            _i5.Future<_i4.BatchUpdateValuesByDataFilterResponse>.value(_FakeBatchUpdateValuesByDataFilterResponse_33(
          this,
          Invocation.method(
            #batchUpdateByDataFilter,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i5.Future<_i4.BatchUpdateValuesByDataFilterResponse>);

  @override
  _i5.Future<_i4.ClearValuesResponse> clear(
    _i3.$Empty? request,
    String? spreadsheetId,
    String? range, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clear,
          [
            request,
            spreadsheetId,
            range,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i5.Future<_i4.ClearValuesResponse>.value(_FakeClearValuesResponse_34(
          this,
          Invocation.method(
            #clear,
            [
              request,
              spreadsheetId,
              range,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i5.Future<_i4.ClearValuesResponse>);

  @override
  _i5.Future<_i4.ValueRange> get(
    String? spreadsheetId,
    String? range, {
    String? dateTimeRenderOption,
    String? majorDimension,
    String? valueRenderOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            spreadsheetId,
            range,
          ],
          {
            #dateTimeRenderOption: dateTimeRenderOption,
            #majorDimension: majorDimension,
            #valueRenderOption: valueRenderOption,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i4.ValueRange>.value(_FakeValueRange_35(
          this,
          Invocation.method(
            #get,
            [
              spreadsheetId,
              range,
            ],
            {
              #dateTimeRenderOption: dateTimeRenderOption,
              #majorDimension: majorDimension,
              #valueRenderOption: valueRenderOption,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i4.ValueRange>);

  @override
  _i5.Future<_i4.UpdateValuesResponse> update(
    _i4.ValueRange? request,
    String? spreadsheetId,
    String? range, {
    bool? includeValuesInResponse,
    String? responseDateTimeRenderOption,
    String? responseValueRenderOption,
    String? valueInputOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            request,
            spreadsheetId,
            range,
          ],
          {
            #includeValuesInResponse: includeValuesInResponse,
            #responseDateTimeRenderOption: responseDateTimeRenderOption,
            #responseValueRenderOption: responseValueRenderOption,
            #valueInputOption: valueInputOption,
            #$fields: $fields,
          },
        ),
        returnValue: _i5.Future<_i4.UpdateValuesResponse>.value(_FakeUpdateValuesResponse_36(
          this,
          Invocation.method(
            #update,
            [
              request,
              spreadsheetId,
              range,
            ],
            {
              #includeValuesInResponse: includeValuesInResponse,
              #responseDateTimeRenderOption: responseDateTimeRenderOption,
              #responseValueRenderOption: responseValueRenderOption,
              #valueInputOption: valueInputOption,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i5.Future<_i4.UpdateValuesResponse>);
}
