// Mocks generated by Mockito 5.4.6 from annotations
// in possystem/test/mocks/mock_bluetooth.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;

import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:packages/bluetooth.dart' as _i2;
import 'package:possystem/components/imageable_container.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePrinterManufactory_0 extends _i1.SmartFake
    implements _i2.PrinterManufactory {
  _FakePrinterManufactory_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBluetoothDevice_1 extends _i1.SmartFake
    implements _i2.BluetoothDevice {
  _FakeBluetoothDevice_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImageableController_2 extends _i1.SmartFake
    implements _i3.ImageableController {
  _FakeImageableController_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_3<T extends _i4.State<_i4.StatefulWidget>>
    extends _i1.SmartFake
    implements _i4.GlobalKey<T> {
  _FakeGlobalKey_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Bluetooth].
///
/// See the documentation for Mockito's code generation for more information.
class MockBluetooth extends _i1.Mock implements _i2.Bluetooth {
  MockBluetooth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.BluetoothDevice>> startScan() =>
      (super.noSuchMethod(
            Invocation.method(#startScan, []),
            returnValue: _i5.Stream<List<_i2.BluetoothDevice>>.empty(),
          )
          as _i5.Stream<List<_i2.BluetoothDevice>>);

  @override
  _i5.Future<void> stopScan() =>
      (super.noSuchMethod(
            Invocation.method(#stopScan, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [Printer].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrinter extends _i1.Mock implements _i2.Printer {
  MockPrinter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get address =>
      (super.noSuchMethod(
            Invocation.getter(#address),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#address),
            ),
          )
          as String);

  @override
  _i2.PrinterManufactory get manufactory =>
      (super.noSuchMethod(
            Invocation.getter(#manufactory),
            returnValue: _FakePrinterManufactory_0(
              this,
              Invocation.getter(#manufactory),
            ),
          )
          as _i2.PrinterManufactory);

  @override
  bool get connected =>
      (super.noSuchMethod(Invocation.getter(#connected), returnValue: false)
          as bool);

  @override
  _i5.Stream<_i2.PrinterStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i5.Stream<_i2.PrinterStatus>.empty(),
          )
          as _i5.Stream<_i2.PrinterStatus>);

  @override
  _i2.BluetoothDevice get device =>
      (super.noSuchMethod(
            Invocation.getter(#device),
            returnValue: _FakeBluetoothDevice_1(
              this,
              Invocation.getter(#device),
            ),
          )
          as _i2.BluetoothDevice);

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<double> draw(
    _i7.Uint8List? image, {
    _i2.PrinterDensity? density,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#draw, [image], {#density: density}),
            returnValue: _i5.Stream<double>.empty(),
          )
          as _i5.Stream<double>);
}

/// A class which mocks [BluetoothDevice].
///
/// See the documentation for Mockito's code generation for more information.
class MockBluetoothDevice extends _i1.Mock implements _i2.BluetoothDevice {
  MockBluetoothDevice() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  String get address =>
      (super.noSuchMethod(
            Invocation.getter(#address),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#address),
            ),
          )
          as String);

  @override
  bool get connected =>
      (super.noSuchMethod(Invocation.getter(#connected), returnValue: false)
          as bool);

  @override
  _i5.Stream<_i2.BluetoothSignal> createSignalStream() =>
      (super.noSuchMethod(
            Invocation.method(#createSignalStream, []),
            returnValue: _i5.Stream<_i2.BluetoothSignal>.empty(),
          )
          as _i5.Stream<_i2.BluetoothSignal>);
}

/// A class which mocks [PrinterManufactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrinterManufactory extends _i1.Mock
    implements _i2.PrinterManufactory {
  MockPrinterManufactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get widthMM =>
      (super.noSuchMethod(Invocation.getter(#widthMM), returnValue: 0) as int);

  @override
  int get widthBits =>
      (super.noSuchMethod(Invocation.getter(#widthBits), returnValue: 0)
          as int);
}

/// A class which mocks [ImageableManger].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageableManger extends _i1.Mock implements _i3.ImageableManger {
  MockImageableManger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ImageableController create() =>
      (super.noSuchMethod(
            Invocation.method(#create, []),
            returnValue: _FakeImageableController_2(
              this,
              Invocation.method(#create, []),
            ),
          )
          as _i3.ImageableController);
}

/// A class which mocks [ImageableController].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageableController extends _i1.Mock
    implements _i3.ImageableController {
  MockImageableController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GlobalKey<_i4.State<_i4.StatefulWidget>> get key =>
      (super.noSuchMethod(
            Invocation.getter(#key),
            returnValue: _FakeGlobalKey_3<_i4.State<_i4.StatefulWidget>>(
              this,
              Invocation.getter(#key),
            ),
          )
          as _i4.GlobalKey<_i4.State<_i4.StatefulWidget>>);

  @override
  _i5.Future<List<_i3.ConvertibleImage>?> toImage({
    required List<int>? widths,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toImage, [], {#widths: widths}),
            returnValue: _i5.Future<List<_i3.ConvertibleImage>?>.value(),
          )
          as _i5.Future<List<_i3.ConvertibleImage>?>);
}
