// Mocks generated by Mockito 5.4.0 from annotations
// in possystem/test/mocks/mock_google_api.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:_discoveryapis_commons/_discoveryapis_commons.dart' as _i5;
import 'package:googleapis/drive/v3.dart' as _i2;
import 'package:googleapis/shared.dart' as _i6;
import 'package:googleapis/sheets/v4.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAboutResource_0 extends _i1.SmartFake implements _i2.AboutResource {
  _FakeAboutResource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChangesResource_1 extends _i1.SmartFake
    implements _i2.ChangesResource {
  _FakeChangesResource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelsResource_2 extends _i1.SmartFake
    implements _i2.ChannelsResource {
  _FakeChannelsResource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommentsResource_3 extends _i1.SmartFake
    implements _i2.CommentsResource {
  _FakeCommentsResource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDrivesResource_4 extends _i1.SmartFake
    implements _i2.DrivesResource {
  _FakeDrivesResource_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFilesResource_5 extends _i1.SmartFake implements _i2.FilesResource {
  _FakeFilesResource_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePermissionsResource_6 extends _i1.SmartFake
    implements _i2.PermissionsResource {
  _FakePermissionsResource_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRepliesResource_7 extends _i1.SmartFake
    implements _i2.RepliesResource {
  _FakeRepliesResource_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRevisionsResource_8 extends _i1.SmartFake
    implements _i2.RevisionsResource {
  _FakeRevisionsResource_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTeamdrivesResource_9 extends _i1.SmartFake
    implements _i2.TeamdrivesResource {
  _FakeTeamdrivesResource_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_10 extends _i1.SmartFake implements _i2.File {
  _FakeFile_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedIds_11 extends _i1.SmartFake implements _i2.GeneratedIds {
  _FakeGeneratedIds_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_12 extends _i1.SmartFake implements Object {
  _FakeObject_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileList_13 extends _i1.SmartFake implements _i2.FileList {
  _FakeFileList_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLabelList_14 extends _i1.SmartFake implements _i2.LabelList {
  _FakeLabelList_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModifyLabelsResponse_15 extends _i1.SmartFake
    implements _i2.ModifyLabelsResponse {
  _FakeModifyLabelsResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpreadsheetsResource_16 extends _i1.SmartFake
    implements _i3.SpreadsheetsResource {
  _FakeSpreadsheetsResource_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpreadsheetsDeveloperMetadataResource_17 extends _i1.SmartFake
    implements _i3.SpreadsheetsDeveloperMetadataResource {
  _FakeSpreadsheetsDeveloperMetadataResource_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpreadsheetsSheetsResource_18 extends _i1.SmartFake
    implements _i3.SpreadsheetsSheetsResource {
  _FakeSpreadsheetsSheetsResource_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpreadsheetsValuesResource_19 extends _i1.SmartFake
    implements _i3.SpreadsheetsValuesResource {
  _FakeSpreadsheetsValuesResource_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchUpdateSpreadsheetResponse_20 extends _i1.SmartFake
    implements _i3.BatchUpdateSpreadsheetResponse {
  _FakeBatchUpdateSpreadsheetResponse_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpreadsheet_21 extends _i1.SmartFake implements _i3.Spreadsheet {
  _FakeSpreadsheet_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppendValuesResponse_22 extends _i1.SmartFake
    implements _i3.AppendValuesResponse {
  _FakeAppendValuesResponse_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchClearValuesResponse_23 extends _i1.SmartFake
    implements _i3.BatchClearValuesResponse {
  _FakeBatchClearValuesResponse_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchClearValuesByDataFilterResponse_24 extends _i1.SmartFake
    implements _i3.BatchClearValuesByDataFilterResponse {
  _FakeBatchClearValuesByDataFilterResponse_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchGetValuesResponse_25 extends _i1.SmartFake
    implements _i3.BatchGetValuesResponse {
  _FakeBatchGetValuesResponse_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchGetValuesByDataFilterResponse_26 extends _i1.SmartFake
    implements _i3.BatchGetValuesByDataFilterResponse {
  _FakeBatchGetValuesByDataFilterResponse_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchUpdateValuesResponse_27 extends _i1.SmartFake
    implements _i3.BatchUpdateValuesResponse {
  _FakeBatchUpdateValuesResponse_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchUpdateValuesByDataFilterResponse_28 extends _i1.SmartFake
    implements _i3.BatchUpdateValuesByDataFilterResponse {
  _FakeBatchUpdateValuesByDataFilterResponse_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClearValuesResponse_29 extends _i1.SmartFake
    implements _i3.ClearValuesResponse {
  _FakeClearValuesResponse_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueRange_30 extends _i1.SmartFake implements _i3.ValueRange {
  _FakeValueRange_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateValuesResponse_31 extends _i1.SmartFake
    implements _i3.UpdateValuesResponse {
  _FakeUpdateValuesResponse_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DriveApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveApi extends _i1.Mock implements _i2.DriveApi {
  MockDriveApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AboutResource get about => (super.noSuchMethod(
        Invocation.getter(#about),
        returnValue: _FakeAboutResource_0(
          this,
          Invocation.getter(#about),
        ),
      ) as _i2.AboutResource);
  @override
  _i2.ChangesResource get changes => (super.noSuchMethod(
        Invocation.getter(#changes),
        returnValue: _FakeChangesResource_1(
          this,
          Invocation.getter(#changes),
        ),
      ) as _i2.ChangesResource);
  @override
  _i2.ChannelsResource get channels => (super.noSuchMethod(
        Invocation.getter(#channels),
        returnValue: _FakeChannelsResource_2(
          this,
          Invocation.getter(#channels),
        ),
      ) as _i2.ChannelsResource);
  @override
  _i2.CommentsResource get comments => (super.noSuchMethod(
        Invocation.getter(#comments),
        returnValue: _FakeCommentsResource_3(
          this,
          Invocation.getter(#comments),
        ),
      ) as _i2.CommentsResource);
  @override
  _i2.DrivesResource get drives => (super.noSuchMethod(
        Invocation.getter(#drives),
        returnValue: _FakeDrivesResource_4(
          this,
          Invocation.getter(#drives),
        ),
      ) as _i2.DrivesResource);
  @override
  _i2.FilesResource get files => (super.noSuchMethod(
        Invocation.getter(#files),
        returnValue: _FakeFilesResource_5(
          this,
          Invocation.getter(#files),
        ),
      ) as _i2.FilesResource);
  @override
  _i2.PermissionsResource get permissions => (super.noSuchMethod(
        Invocation.getter(#permissions),
        returnValue: _FakePermissionsResource_6(
          this,
          Invocation.getter(#permissions),
        ),
      ) as _i2.PermissionsResource);
  @override
  _i2.RepliesResource get replies => (super.noSuchMethod(
        Invocation.getter(#replies),
        returnValue: _FakeRepliesResource_7(
          this,
          Invocation.getter(#replies),
        ),
      ) as _i2.RepliesResource);
  @override
  _i2.RevisionsResource get revisions => (super.noSuchMethod(
        Invocation.getter(#revisions),
        returnValue: _FakeRevisionsResource_8(
          this,
          Invocation.getter(#revisions),
        ),
      ) as _i2.RevisionsResource);
  @override
  _i2.TeamdrivesResource get teamdrives => (super.noSuchMethod(
        Invocation.getter(#teamdrives),
        returnValue: _FakeTeamdrivesResource_9(
          this,
          Invocation.getter(#teamdrives),
        ),
      ) as _i2.TeamdrivesResource);
}

/// A class which mocks [FilesResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilesResource extends _i1.Mock implements _i2.FilesResource {
  MockFilesResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.File> copy(
    _i2.File? request,
    String? fileId, {
    bool? enforceSingleParent,
    bool? ignoreDefaultVisibility,
    String? includeLabels,
    String? includePermissionsForView,
    bool? keepRevisionForever,
    String? ocrLanguage,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copy,
          [
            request,
            fileId,
          ],
          {
            #enforceSingleParent: enforceSingleParent,
            #ignoreDefaultVisibility: ignoreDefaultVisibility,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #keepRevisionForever: keepRevisionForever,
            #ocrLanguage: ocrLanguage,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<_i2.File>.value(_FakeFile_10(
          this,
          Invocation.method(
            #copy,
            [
              request,
              fileId,
            ],
            {
              #enforceSingleParent: enforceSingleParent,
              #ignoreDefaultVisibility: ignoreDefaultVisibility,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #keepRevisionForever: keepRevisionForever,
              #ocrLanguage: ocrLanguage,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i4.Future<_i2.File>);
  @override
  _i4.Future<_i2.File> create(
    _i2.File? request, {
    bool? enforceSingleParent,
    bool? ignoreDefaultVisibility,
    String? includeLabels,
    String? includePermissionsForView,
    bool? keepRevisionForever,
    String? ocrLanguage,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    bool? useContentAsIndexableText,
    String? $fields,
    _i5.UploadOptions? uploadOptions = _i5.UploadOptions.defaultOptions,
    _i5.Media? uploadMedia,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [request],
          {
            #enforceSingleParent: enforceSingleParent,
            #ignoreDefaultVisibility: ignoreDefaultVisibility,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #keepRevisionForever: keepRevisionForever,
            #ocrLanguage: ocrLanguage,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #useContentAsIndexableText: useContentAsIndexableText,
            #$fields: $fields,
            #uploadOptions: uploadOptions,
            #uploadMedia: uploadMedia,
          },
        ),
        returnValue: _i4.Future<_i2.File>.value(_FakeFile_10(
          this,
          Invocation.method(
            #create,
            [request],
            {
              #enforceSingleParent: enforceSingleParent,
              #ignoreDefaultVisibility: ignoreDefaultVisibility,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #keepRevisionForever: keepRevisionForever,
              #ocrLanguage: ocrLanguage,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #useContentAsIndexableText: useContentAsIndexableText,
              #$fields: $fields,
              #uploadOptions: uploadOptions,
              #uploadMedia: uploadMedia,
            },
          ),
        )),
      ) as _i4.Future<_i2.File>);
  @override
  _i4.Future<void> delete(
    String? fileId, {
    bool? enforceSingleParent,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [fileId],
          {
            #enforceSingleParent: enforceSingleParent,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> emptyTrash({
    bool? enforceSingleParent,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #emptyTrash,
          [],
          {
            #enforceSingleParent: enforceSingleParent,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i5.Media?> export(
    String? fileId,
    String? mimeType, {
    String? $fields,
    _i5.DownloadOptions? downloadOptions = _i5.DownloadOptions.metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #export,
          [
            fileId,
            mimeType,
          ],
          {
            #$fields: $fields,
            #downloadOptions: downloadOptions,
          },
        ),
        returnValue: _i4.Future<_i5.Media?>.value(),
      ) as _i4.Future<_i5.Media?>);
  @override
  _i4.Future<_i2.GeneratedIds> generateIds({
    int? count,
    String? space,
    String? type,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateIds,
          [],
          {
            #count: count,
            #space: space,
            #type: type,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<_i2.GeneratedIds>.value(_FakeGeneratedIds_11(
          this,
          Invocation.method(
            #generateIds,
            [],
            {
              #count: count,
              #space: space,
              #type: type,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i4.Future<_i2.GeneratedIds>);
  @override
  _i4.Future<Object> get(
    String? fileId, {
    bool? acknowledgeAbuse,
    String? includeLabels,
    String? includePermissionsForView,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
    _i5.DownloadOptions? downloadOptions = _i5.DownloadOptions.metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [fileId],
          {
            #acknowledgeAbuse: acknowledgeAbuse,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
            #downloadOptions: downloadOptions,
          },
        ),
        returnValue: _i4.Future<Object>.value(_FakeObject_12(
          this,
          Invocation.method(
            #get,
            [fileId],
            {
              #acknowledgeAbuse: acknowledgeAbuse,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #$fields: $fields,
              #downloadOptions: downloadOptions,
            },
          ),
        )),
      ) as _i4.Future<Object>);
  @override
  _i4.Future<_i2.FileList> list({
    String? corpora,
    String? corpus,
    String? driveId,
    bool? includeItemsFromAllDrives,
    String? includeLabels,
    String? includePermissionsForView,
    bool? includeTeamDriveItems,
    String? orderBy,
    int? pageSize,
    String? pageToken,
    String? q,
    String? spaces,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? teamDriveId,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #corpora: corpora,
            #corpus: corpus,
            #driveId: driveId,
            #includeItemsFromAllDrives: includeItemsFromAllDrives,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #includeTeamDriveItems: includeTeamDriveItems,
            #orderBy: orderBy,
            #pageSize: pageSize,
            #pageToken: pageToken,
            #q: q,
            #spaces: spaces,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #teamDriveId: teamDriveId,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<_i2.FileList>.value(_FakeFileList_13(
          this,
          Invocation.method(
            #list,
            [],
            {
              #corpora: corpora,
              #corpus: corpus,
              #driveId: driveId,
              #includeItemsFromAllDrives: includeItemsFromAllDrives,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #includeTeamDriveItems: includeTeamDriveItems,
              #orderBy: orderBy,
              #pageSize: pageSize,
              #pageToken: pageToken,
              #q: q,
              #spaces: spaces,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #teamDriveId: teamDriveId,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i4.Future<_i2.FileList>);
  @override
  _i4.Future<_i2.LabelList> listLabels(
    String? fileId, {
    int? maxResults,
    String? pageToken,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLabels,
          [fileId],
          {
            #maxResults: maxResults,
            #pageToken: pageToken,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<_i2.LabelList>.value(_FakeLabelList_14(
          this,
          Invocation.method(
            #listLabels,
            [fileId],
            {
              #maxResults: maxResults,
              #pageToken: pageToken,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i4.Future<_i2.LabelList>);
  @override
  _i4.Future<_i2.ModifyLabelsResponse> modifyLabels(
    _i2.ModifyLabelsRequest? request,
    String? fileId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modifyLabels,
          [
            request,
            fileId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i4.Future<_i2.ModifyLabelsResponse>.value(
            _FakeModifyLabelsResponse_15(
          this,
          Invocation.method(
            #modifyLabels,
            [
              request,
              fileId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i4.Future<_i2.ModifyLabelsResponse>);
  @override
  _i4.Future<_i2.File> update(
    _i2.File? request,
    String? fileId, {
    String? addParents,
    bool? enforceSingleParent,
    String? includeLabels,
    String? includePermissionsForView,
    bool? keepRevisionForever,
    String? ocrLanguage,
    String? removeParents,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    bool? useContentAsIndexableText,
    String? $fields,
    _i5.UploadOptions? uploadOptions = _i5.UploadOptions.defaultOptions,
    _i5.Media? uploadMedia,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            request,
            fileId,
          ],
          {
            #addParents: addParents,
            #enforceSingleParent: enforceSingleParent,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #keepRevisionForever: keepRevisionForever,
            #ocrLanguage: ocrLanguage,
            #removeParents: removeParents,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #useContentAsIndexableText: useContentAsIndexableText,
            #$fields: $fields,
            #uploadOptions: uploadOptions,
            #uploadMedia: uploadMedia,
          },
        ),
        returnValue: _i4.Future<_i2.File>.value(_FakeFile_10(
          this,
          Invocation.method(
            #update,
            [
              request,
              fileId,
            ],
            {
              #addParents: addParents,
              #enforceSingleParent: enforceSingleParent,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #keepRevisionForever: keepRevisionForever,
              #ocrLanguage: ocrLanguage,
              #removeParents: removeParents,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #useContentAsIndexableText: useContentAsIndexableText,
              #$fields: $fields,
              #uploadOptions: uploadOptions,
              #uploadMedia: uploadMedia,
            },
          ),
        )),
      ) as _i4.Future<_i2.File>);
  @override
  _i4.Future<Object> watch(
    _i6.$Channel00? request,
    String? fileId, {
    bool? acknowledgeAbuse,
    String? includeLabels,
    String? includePermissionsForView,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
    _i5.DownloadOptions? downloadOptions = _i5.DownloadOptions.metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [
            request,
            fileId,
          ],
          {
            #acknowledgeAbuse: acknowledgeAbuse,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
            #downloadOptions: downloadOptions,
          },
        ),
        returnValue: _i4.Future<Object>.value(_FakeObject_12(
          this,
          Invocation.method(
            #watch,
            [
              request,
              fileId,
            ],
            {
              #acknowledgeAbuse: acknowledgeAbuse,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #$fields: $fields,
              #downloadOptions: downloadOptions,
            },
          ),
        )),
      ) as _i4.Future<Object>);
}

/// A class which mocks [SheetsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSheetsApi extends _i1.Mock implements _i3.SheetsApi {
  MockSheetsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SpreadsheetsResource get spreadsheets => (super.noSuchMethod(
        Invocation.getter(#spreadsheets),
        returnValue: _FakeSpreadsheetsResource_16(
          this,
          Invocation.getter(#spreadsheets),
        ),
      ) as _i3.SpreadsheetsResource);
}

/// A class which mocks [SpreadsheetsResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpreadsheetsResource extends _i1.Mock
    implements _i3.SpreadsheetsResource {
  MockSpreadsheetsResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SpreadsheetsDeveloperMetadataResource get developerMetadata =>
      (super.noSuchMethod(
        Invocation.getter(#developerMetadata),
        returnValue: _FakeSpreadsheetsDeveloperMetadataResource_17(
          this,
          Invocation.getter(#developerMetadata),
        ),
      ) as _i3.SpreadsheetsDeveloperMetadataResource);
  @override
  _i3.SpreadsheetsSheetsResource get sheets => (super.noSuchMethod(
        Invocation.getter(#sheets),
        returnValue: _FakeSpreadsheetsSheetsResource_18(
          this,
          Invocation.getter(#sheets),
        ),
      ) as _i3.SpreadsheetsSheetsResource);
  @override
  _i3.SpreadsheetsValuesResource get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: _FakeSpreadsheetsValuesResource_19(
          this,
          Invocation.getter(#values),
        ),
      ) as _i3.SpreadsheetsValuesResource);
  @override
  _i4.Future<_i3.BatchUpdateSpreadsheetResponse> batchUpdate(
    _i3.BatchUpdateSpreadsheetRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i4.Future<_i3.BatchUpdateSpreadsheetResponse>.value(
            _FakeBatchUpdateSpreadsheetResponse_20(
          this,
          Invocation.method(
            #batchUpdate,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i4.Future<_i3.BatchUpdateSpreadsheetResponse>);
  @override
  _i4.Future<_i3.Spreadsheet> create(
    _i3.Spreadsheet? request, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [request],
          {#$fields: $fields},
        ),
        returnValue: _i4.Future<_i3.Spreadsheet>.value(_FakeSpreadsheet_21(
          this,
          Invocation.method(
            #create,
            [request],
            {#$fields: $fields},
          ),
        )),
      ) as _i4.Future<_i3.Spreadsheet>);
  @override
  _i4.Future<_i3.Spreadsheet> get(
    String? spreadsheetId, {
    bool? includeGridData,
    List<String>? ranges,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [spreadsheetId],
          {
            #includeGridData: includeGridData,
            #ranges: ranges,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<_i3.Spreadsheet>.value(_FakeSpreadsheet_21(
          this,
          Invocation.method(
            #get,
            [spreadsheetId],
            {
              #includeGridData: includeGridData,
              #ranges: ranges,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i4.Future<_i3.Spreadsheet>);
  @override
  _i4.Future<_i3.Spreadsheet> getByDataFilter(
    _i3.GetSpreadsheetByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByDataFilter,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i4.Future<_i3.Spreadsheet>.value(_FakeSpreadsheet_21(
          this,
          Invocation.method(
            #getByDataFilter,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i4.Future<_i3.Spreadsheet>);
}

/// A class which mocks [SpreadsheetsValuesResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpreadsheetsValuesResource extends _i1.Mock
    implements _i3.SpreadsheetsValuesResource {
  MockSpreadsheetsValuesResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.AppendValuesResponse> append(
    _i3.ValueRange? request,
    String? spreadsheetId,
    String? range, {
    bool? includeValuesInResponse,
    String? insertDataOption,
    String? responseDateTimeRenderOption,
    String? responseValueRenderOption,
    String? valueInputOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #append,
          [
            request,
            spreadsheetId,
            range,
          ],
          {
            #includeValuesInResponse: includeValuesInResponse,
            #insertDataOption: insertDataOption,
            #responseDateTimeRenderOption: responseDateTimeRenderOption,
            #responseValueRenderOption: responseValueRenderOption,
            #valueInputOption: valueInputOption,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<_i3.AppendValuesResponse>.value(
            _FakeAppendValuesResponse_22(
          this,
          Invocation.method(
            #append,
            [
              request,
              spreadsheetId,
              range,
            ],
            {
              #includeValuesInResponse: includeValuesInResponse,
              #insertDataOption: insertDataOption,
              #responseDateTimeRenderOption: responseDateTimeRenderOption,
              #responseValueRenderOption: responseValueRenderOption,
              #valueInputOption: valueInputOption,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i4.Future<_i3.AppendValuesResponse>);
  @override
  _i4.Future<_i3.BatchClearValuesResponse> batchClear(
    _i3.BatchClearValuesRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchClear,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i4.Future<_i3.BatchClearValuesResponse>.value(
            _FakeBatchClearValuesResponse_23(
          this,
          Invocation.method(
            #batchClear,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i4.Future<_i3.BatchClearValuesResponse>);
  @override
  _i4.Future<_i3.BatchClearValuesByDataFilterResponse> batchClearByDataFilter(
    _i3.BatchClearValuesByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchClearByDataFilter,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i4.Future<_i3.BatchClearValuesByDataFilterResponse>.value(
            _FakeBatchClearValuesByDataFilterResponse_24(
          this,
          Invocation.method(
            #batchClearByDataFilter,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i4.Future<_i3.BatchClearValuesByDataFilterResponse>);
  @override
  _i4.Future<_i3.BatchGetValuesResponse> batchGet(
    String? spreadsheetId, {
    String? dateTimeRenderOption,
    String? majorDimension,
    List<String>? ranges,
    String? valueRenderOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchGet,
          [spreadsheetId],
          {
            #dateTimeRenderOption: dateTimeRenderOption,
            #majorDimension: majorDimension,
            #ranges: ranges,
            #valueRenderOption: valueRenderOption,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<_i3.BatchGetValuesResponse>.value(
            _FakeBatchGetValuesResponse_25(
          this,
          Invocation.method(
            #batchGet,
            [spreadsheetId],
            {
              #dateTimeRenderOption: dateTimeRenderOption,
              #majorDimension: majorDimension,
              #ranges: ranges,
              #valueRenderOption: valueRenderOption,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i4.Future<_i3.BatchGetValuesResponse>);
  @override
  _i4.Future<_i3.BatchGetValuesByDataFilterResponse> batchGetByDataFilter(
    _i3.BatchGetValuesByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchGetByDataFilter,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i4.Future<_i3.BatchGetValuesByDataFilterResponse>.value(
            _FakeBatchGetValuesByDataFilterResponse_26(
          this,
          Invocation.method(
            #batchGetByDataFilter,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i4.Future<_i3.BatchGetValuesByDataFilterResponse>);
  @override
  _i4.Future<_i3.BatchUpdateValuesResponse> batchUpdate(
    _i3.BatchUpdateValuesRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdate,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i4.Future<_i3.BatchUpdateValuesResponse>.value(
            _FakeBatchUpdateValuesResponse_27(
          this,
          Invocation.method(
            #batchUpdate,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i4.Future<_i3.BatchUpdateValuesResponse>);
  @override
  _i4.Future<_i3.BatchUpdateValuesByDataFilterResponse> batchUpdateByDataFilter(
    _i3.BatchUpdateValuesByDataFilterRequest? request,
    String? spreadsheetId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateByDataFilter,
          [
            request,
            spreadsheetId,
          ],
          {#$fields: $fields},
        ),
        returnValue:
            _i4.Future<_i3.BatchUpdateValuesByDataFilterResponse>.value(
                _FakeBatchUpdateValuesByDataFilterResponse_28(
          this,
          Invocation.method(
            #batchUpdateByDataFilter,
            [
              request,
              spreadsheetId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i4.Future<_i3.BatchUpdateValuesByDataFilterResponse>);
  @override
  _i4.Future<_i3.ClearValuesResponse> clear(
    _i6.$Empty? request,
    String? spreadsheetId,
    String? range, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clear,
          [
            request,
            spreadsheetId,
            range,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i4.Future<_i3.ClearValuesResponse>.value(
            _FakeClearValuesResponse_29(
          this,
          Invocation.method(
            #clear,
            [
              request,
              spreadsheetId,
              range,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i4.Future<_i3.ClearValuesResponse>);
  @override
  _i4.Future<_i3.ValueRange> get(
    String? spreadsheetId,
    String? range, {
    String? dateTimeRenderOption,
    String? majorDimension,
    String? valueRenderOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            spreadsheetId,
            range,
          ],
          {
            #dateTimeRenderOption: dateTimeRenderOption,
            #majorDimension: majorDimension,
            #valueRenderOption: valueRenderOption,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<_i3.ValueRange>.value(_FakeValueRange_30(
          this,
          Invocation.method(
            #get,
            [
              spreadsheetId,
              range,
            ],
            {
              #dateTimeRenderOption: dateTimeRenderOption,
              #majorDimension: majorDimension,
              #valueRenderOption: valueRenderOption,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i4.Future<_i3.ValueRange>);
  @override
  _i4.Future<_i3.UpdateValuesResponse> update(
    _i3.ValueRange? request,
    String? spreadsheetId,
    String? range, {
    bool? includeValuesInResponse,
    String? responseDateTimeRenderOption,
    String? responseValueRenderOption,
    String? valueInputOption,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            request,
            spreadsheetId,
            range,
          ],
          {
            #includeValuesInResponse: includeValuesInResponse,
            #responseDateTimeRenderOption: responseDateTimeRenderOption,
            #responseValueRenderOption: responseValueRenderOption,
            #valueInputOption: valueInputOption,
            #$fields: $fields,
          },
        ),
        returnValue: _i4.Future<_i3.UpdateValuesResponse>.value(
            _FakeUpdateValuesResponse_31(
          this,
          Invocation.method(
            #update,
            [
              request,
              spreadsheetId,
              range,
            ],
            {
              #includeValuesInResponse: includeValuesInResponse,
              #responseDateTimeRenderOption: responseDateTimeRenderOption,
              #responseValueRenderOption: responseValueRenderOption,
              #valueInputOption: valueInputOption,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i4.Future<_i3.UpdateValuesResponse>);
}
