# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Test locally"
  lane :test do
    sh "flutter build appbundle -v --flavor dev"

    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/devRelease/app-dev-release.aab',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      sync_image_upload: false,
      validate_only: true,
      json_key: "fastlane-keys.json",
    )
  end

  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    sh "flutter build appbundle -v --flavor dev --dart-define=appFlavor=dev --dart-define=logLevel=info"

    upload_to_play_store(
      track: 'internal',
      rollout: '1',
      aab: '../build/app/outputs/bundle/devRelease/app-dev-release.aab',
      skip_upload_metadata: true,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      sync_image_upload: false,
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    sh "flutter build appbundle -v --flavor prod --dart-define=appFlavor=prod --dart-define=logLevel=info"

    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab',
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: false,
      sync_image_upload: true,
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
    )
  end

  desc "Promote beta track to prod"
  lane :promote_to_production do
    upload_to_play_store(
      track: 'beta',
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: false,
      sync_image_upload: true,
      track_promote_to: 'production',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
      version_code: ENV['VERSION_CODE'],
    )
  end
end
